### ISSUE TITLE
RCLoot Recode

### ISSUE THREAD

**Issue by Silthus** [raidcraft/raidcraft#24]
Das RCLoot Plugin ist in recht gutem Zustand und kann vermutlich mit wenig Aufwand neu programmiert werden. Später würde ich dort dann auch die Loot Chests (MysteryChests) mit aufnehmen.

Hier mal ein Vorschlag für die Config Syntax:

```yaml
rarities:
  common:
    # die default chance die alle loot objekte mit dieser rarität erhalten
    chance: 20
    name: "&a&l%loot_object%%r"
loot-objects:
  money-2000:
    type: money
    # the name is formatted with the rarity and displayed
    # in the preview and chat broadcast
    name: 2000c
    # lore is only displayed in preview and result view
    # or under the item in holographic displays
    # not in the chat broadcast
    lore: >-
      &6a Super duper money!
      eaz multi line lore...
    # not required if rarity is set but can overwrite rarity chance
    # chance: 25
    rarity: common
    # Einfacher Schalter um das Loot-Objekt zu deaktivieren,
    # ohne es aus der Config löschen zu müssen.
    enabled: true
    # Wenn true wird das Objekt dem Ergebnis immer hinzugefügt, egal was für eine Wahrscheinlichkeit oder Count konfiguriert ist.
    # Wenn die Objekte mit always den Count überschreiten werden alle always Objekte hinzugefügt.
    always: false
    # Das Objekt wird nur ein einziges Mal dem Ergebnis hinzugefügt.
    unique: false
    # Die Wahrscheinlichkeit in Abhängigkeit der anderen Wahrscheinlichkeiten.
    # Die probability ist keine reine % Angabe.
    probability: 1
    # Zählt die Wahrscheinlichkeit der Tabelle nicht mit in die Gesamtgewichtung.
    # Items können nur durch das always Flag droppen.
    # Ist z.B. nützlich um eine extra Tabelle immer droppen zu lassen,
    # aber in der referenzierten Tabelle eigene Wahrscheinlichkeiten zu definieren.
    exclude-from-random: false
    with:
      amount: 2000
  diamonds:
    type: item
    name: "%amount%x Diamanten"
    chance: 0.05
    with:
      # the actual amount can be specified by the consuming loot table
      item: 'minecraft:diamond'

loot-tables:
  eastereggs:
    count: 5
    rewards:
      - object: red_egg
      - object: green_egg
  # in der vorschau werden alle items die gelootet werden können zusammen geschmissen
  # und eine chance basierend auf der chance und dem count berechnet
  example:
    # Optionale Metadaten die im Loot Admin Menü angezeigt werden.
    # Macht es Quest Scriptern und Entwicklern leichter Loot-Tabellen auszuwählen.
    # Alle Daten sind optional und müssen nicht angegeben werden.
    meta:
      # Ein prägnanter Name für die Loot-Tabelle,
      # z.B. Äpfel Ankanor
      name: 'Optionaler Anzeige Name'
      # Eine kurze Beschreibung wozu die Loot-Tabelle dienen soll,
      # z.B. "Äpfel die bei Bäumen in Ankanor liegen oder dran hängen."
      desc: 'Beschreibung der Loot-Tabelle'
      # Das Icon im Loot Admin Menü.
      icon: 'minecraft:apple'
    # Kann weggelassen werden da es der default ist.
    type: table
    # kann man auf false schalten um die tabelle zu deaktivieren
    enabled: true
    # auf true setzen um dem spieler die tatsächliche chance (berechnet anhand aller loot objekte) anzuzeigen
    show-chance: false
    # Der count der Tabelle die am höchsten definiert ist zählt.
    # Sobald diese Anzahl an Items erreicht ist wird nicht weiter gelootet.
    count: 1
    # Die entries Sektion kann weitere Loot-Tabellen und Objekte enthalten.
    rewards:
    # es gibt die folgenden reward types:
    # object - eins der vordefinierten loot objekte
    # table - eine der definierten loot tabellen
    # type - ein inline loot objekt
    - object: money-2000
      chance: 10
      # dieser reward kann maximal zwei mal vorkommen
      # wird count weggelassen kann der reward nur einmal vorkommen
      # ein count von 2 verdoppelt quasi die chance dieses loot objekts
      count: 2
    - object: diamonds
      always: true
      with:
        # !Wichtig! amount ist etwas anderes als count
        # obwohl der Spieler 12 Diamanten bekommt zählt das nur
        # als 1 count da es ein einziges loot objekt ist
        amount: 12
    - type: item
      chance: 33
      count: 1
      with:
        item: coal_ore
    - table: eastereggs
      chance: 33
      # überschreibt den counter der loot-tabelle von oben (5)
      # der counter bezieht sich immer auf die gesamte anzahl der loot objekte 
      # ab diesem loot-baum
      # ist der count der "root" loot tabelle erreicht wird nicht weiter gelootet
      count: 1
```
